### PR TITLE
Fix the out of bound issue

### PR DESCRIPTION
**Pull request by yarkinwho**
This approach is giving extra buffer for the inputs.

### CODE REVIEW

**Comment by mschoenebeck** [comment]
Thanks for the new PR to resolve this issue. Do the unit tests on your machine succeed? When running `./test/unittests` on my machine it throws:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  signatures must be equal
Aborted (core dumped)
```
in this line:
https://github.com/mschoenebeck/bls12-381/blob/71a180eae5b3e40ba5f9fa67d9d2998408640306/test/unittests.cpp#L1340

**Comment by yarkinwho** [comment]
that's weird. let me try running it on other machines.

**Comment by yarkinwho** [comment]
Now it should not fail the tests. Please check that.

The issue is, the quotient and remainder also has overflow issues, it's just somehow not exposed.
But with the new buffer in stack with the above fix, it's exposed.

**Comment by mschoenebeck** [comment]
Yep, now it works. Thanks for the update. Gonna merge it now into `main` as well as the `leap` branch.

**Pull request merged**
