### PR TITLE
Yarkin/fix out of bound 

### PR DESCRIPTION
**Pull request by yarkinwho**

### CODE REVIEW

**Comment by mschoenebeck** [comment]
Trying to compile the code on my machine using g++ throws:

```
/home/mschoenebeck/dev/bls12-381/src/scalar.cpp: In function ‘void bls12_381::bn_divn_low(uint64_t*, uint64_t*, const uint64_t*, int, const uint64_t*, int)’:
/home/mschoenebeck/dev/bls12-381/src/scalar.cpp:349:5: error: ‘assert’ was not declared in this scope
  349 |     assert(sa >= sb);
      |     ^~~~~~
/home/mschoenebeck/dev/bls12-381/src/scalar.cpp:2:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
    1 | #include <bls12_381.hpp>
  +++ |+#include <cassert>
    2 | 
make[2]: *** [src/CMakeFiles/bls12_381.dir/build.make:132: src/CMakeFiles/bls12_381.dir/scalar.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:136: src/CMakeFiles/bls12_381.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

seems like an include is missing

**Comment by mschoenebeck** [comment]
Also the library name changed from `bls12_381` to `bls12-381`. I know, it's annoying..

**Comment by mschoenebeck** [comment]
Did you benchmark your new `bn_divn_low` implementation? On my machine it slows down the code significantly. The compiler inserts almost 200 more instructions. Here are the benchmarks on my machine from before/after:

before:
```
bn_divn_low
Total: 5000000 runs in 375 ms
Avg: 7.5e-05 ms

bn_divn_low
Total: 5000000 runs in 371 ms
Avg: 7.42e-05 ms

bn_divn_low
Total: 5000000 runs in 378 ms
Avg: 7.56e-05 ms
```

after:
```
bn_divn_low
Total: 5000000 runs in 633 ms
Avg: 0.0001266 ms

bn_divn_low
Total: 5000000 runs in 637 ms
Avg: 0.0001274 ms

bn_divn_low
Total: 5000000 runs in 632 ms
Avg: 0.0001264 ms
```

From what I understand, the issue you are trying to solve is [described here](https://github.com/relic-toolkit/relic/blob/ddd1984a76aa9c96a12ebdf5c6786b0ee6a26ef8/src/bn/relic_bn_div.c#L79) and has a simple solution, which is just increasing the amount of 'scratch' memory for the operands.

When I borrowed the code from `relic-toolkit` and started working with it, I found that for `gcc` it didn't lead to the memory issue. It was only when @spoonincode started testing with `clang` we ran into the issue. So we increased the memory **for some operands** a bit, which solved it. Now on ARM you still seem to have the issue, so I would recommend we just increase the memory of the remaining operands to the same extend they did in relic (see link above). That should solve it and we don't have to touch the highly optimized and widely adopted relic code, slowing it down significantly.

Now, unfortunately, I have no ARM machine to reproduce the problem, but if you could solve it by just increasing the corresponding operand arrays before `bn_divn_low` is called, without changing the implementation itself, that would be the better solution imo, since it wouldn't affect performance at all and comes at the very cheap cost of allocating just one more word or something.

The only reason we reach the same benchmarks for modular reduction as GMP is precisely because of this relic fallback implementation for `bn_divn_low`, which I borrowed from their code. I wouldn't want to touch this tbh but rather follow their advice in the comment linked above.

**Comment by yarkinwho** [comment]
> Did you benchmark your new `bn_divn_low` implementation? On my machine it slows down the code significantly. The compiler inserts almost 200 more instructions. Here are the benchmarks on my machine from before/after:
> 
> before:
> 
> ```
> bn_divn_low
> Total: 5000000 runs in 375 ms
> Avg: 7.5e-05 ms
> 
> bn_divn_low
> Total: 5000000 runs in 371 ms
> Avg: 7.42e-05 ms
> 
> bn_divn_low
> Total: 5000000 runs in 378 ms
> Avg: 7.56e-05 ms
> ```
> 
> after:
> 
> ```
> bn_divn_low
> Total: 5000000 runs in 633 ms
> Avg: 0.0001266 ms
> 
> bn_divn_low
> Total: 5000000 runs in 637 ms
> Avg: 0.0001274 ms
> 
> bn_divn_low
> Total: 5000000 runs in 632 ms
> Avg: 0.0001264 ms
> ```
> 
> From what I understand, the issue you are trying to solve is [described here](https://github.com/relic-toolkit/relic/blob/ddd1984a76aa9c96a12ebdf5c6786b0ee6a26ef8/src/bn/relic_bn_div.c#L79) and has a simple solution, which is just increasing the amount of 'scratch' memory for the operands.
> 
> When I borrowed the code from `relic-toolkit` and started working with it, I found that for `gcc` it didn't lead to the memory issue. It was only when @spoonincode started testing with `clang` we ran into the issue. So we increased the memory **for some operands** a bit, which solved it. Now on ARM you still seem to have the issue, so I would recommend we just increase the memory of the remaining operands to the same extend they did in relic (see link above). That should solve it and we don't have to touch the highly optimized and widely adopted relic code, slowing it down significantly.
> 
> Now, unfortunately, I have no ARM machine to reproduce the problem, but if you could solve it by just increasing the corresponding operand arrays before `bn_divn_low` is called, without changing the implementation itself, that would be the better solution imo, since it wouldn't affect performance at all and comes at the very cheap cost of allocating just one more word or something.
> 
> The only reason we reach the same benchmarks for modular reduction as GMP is precisely because of this relic fallback implementation for `bn_divn_low`, which I borrowed from their code. I wouldn't want to touch this tbh but rather follow their advice in the comment linked above.

The impact on the final result would not be that significant as if you allocate memory inside the function, you can skip the same step outside the function (exactly what the "scratch" approach does). If you evaluate the performance of high level operations such as sign or verification, you will not see significant difference.

But I am also fine with only scratch the memory outside the function, but in that case, extra comments is needed as a method of warning to prevent other people from copying the bn_divn_low without noticing this issue.

As for the compiler, it doesn't matter, the out of bound visit is a clear problem. We should not simply let it go if say the complier we use somehow avoids triggering the bug.

**Comment by yarkinwho** [comment]
> Trying to compile the code on my machine using g++ throws:
> 
> ```
> /home/mschoenebeck/dev/bls12-381/src/scalar.cpp: In function ‘void bls12_381::bn_divn_low(uint64_t*, uint64_t*, const uint64_t*, int, const uint64_t*, int)’:
> /home/mschoenebeck/dev/bls12-381/src/scalar.cpp:349:5: error: ‘assert’ was not declared in this scope
>   349 |     assert(sa >= sb);
>       |     ^~~~~~
> /home/mschoenebeck/dev/bls12-381/src/scalar.cpp:2:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
>     1 | #include <bls12_381.hpp>
>   +++ |+#include <cassert>
>     2 | 
> make[2]: *** [src/CMakeFiles/bls12_381.dir/build.make:132: src/CMakeFiles/bls12_381.dir/scalar.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:136: src/CMakeFiles/bls12_381.dir/all] Error 2
> make: *** [Makefile:101: all] Error 2
> ```
> 
> seems like an include is missing

yeah, miss some include here i believe... it's strange how it compiles on mac....

**Comment by yarkinwho** [comment]
we decided use some cheaper way to fix it #6

**Pull request closed without merging**
